### ISSUE TITLE
How to deploy as a master-slave configuration?

### ISSUE THREAD

**Issue by ashishjain14** [cloudfoundry-community/postgres-boshrelease#14]
Can this postgres-boshrelease be deployed in a master slave configuration? Can you please provide any details? Currently when I deploy using this https://github.com/cloudfoundry-community/postgres-boshrelease/blob/master/templates/jobs.yml#L16, I am able to deploy 3 instances where I see all the instances are able to create users. So is it being deployed as 3 independent standalone instances or is there any configuration which I am missing?

**Comment by jhunt** [comment]
The example sets up a 3-node replicated cluster (on non-standard port 6432) and fronts it with pgpool running on all three nodes on the standard 5432 port.

**Comment by ashishjain14** [comment]
Thanks James, closing this issue.
