### ISSUE TITLE
ha mode question

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/postgres-boshrelease#23]
Hi. Is it possible to use dns + haproxy without vip configuration at AWS?

**Comment by jhunt** [comment]
Not currently, no, although it should be a trivial change to introduce a `vip: null` or `vip: false` case into the templates to avoid the VRRP stuff but still use haproxy for master/replica status.

**Comment by jhunt** [comment]
Handled in #24

**Comment by jhunt** [comment]
(which is released in v3.1.0: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/tag/v3.1.0)
