### ISSUE TITLE
what is the relationship between this repo and cloudfoundry/postgres-release

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry-community/postgres-boshrelease#29]
I found there is another repo https://github.com/cloudfoundry/postgres-release also provide as postgres bosh release. But it doesn't provide as many senior features(ha) as this one. So why there are two postgres bosh release?

**Comment by jhunt** [comment]
We do not have access to change things in the `cloudfoundry` Github organization, and we needed additional functionality.
