### ISSUE TITLE
create user with database creation role

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/postgres-boshrelease#3]
how can you create a user with database/user creation rights (supersuer) with pgpool
because i can't find this anywhere in the pgpool documentation

so i was wondering if maby you can help me out here

**Comment by ramonskie** [comment]
tried to use psql on the master
with psql -p 6432 - h localhost -U vcap
but i keeps asking for a password
even when the vcap user is trusted

**Comment by jhunt** [comment]
Is that the literal command you are running?  There seems to be a space between the `-` and the `h` flag...

**Comment by ramonskie** [comment]
:) no thats a typo here
if that would be the case psql wouldn't asked for a password.

what i ultimately want to achieve is that i have a root user who can create databases and users
so i can use this for our terraform templates

**Comment by jhunt** [comment]
Have you tried:

```
psql -p 6432 -h localhost -U vcap postgres
```

What we probably need to do is modify the job to do grants based on configuration in the manifest, on or around here:

https://github.com/cloudfoundry-community/postgres-boshrelease/blob/master/jobs/postgres/templates/bin/ctl#L115-L116

**Comment by ramonskie** [comment]
i tried that but still asking for a password
i tried to use the default root password but no dice

```
bosh_h3fijfro@175a90a4-e1b4-4ee0-beb6-d683a300f0d8:~$ /var/vcap/data/packages/postgres/a72141d28d97c02c4348633d31995953e75a6183.1-395e2f3ea55cd7da9a3ad3dac9f26669250ac4d9/bin/psql -p 6432 -h localhost -U vcap postgres
Password for user vcap: 
psql: FATAL:  password authentication failed for user "vcap"
```

postgres.log

```
FATAL:  password authentication failed for user "root"
DETAIL:  Connection matched pg_hba.conf line 7: "local all all md5"
FATAL:  password authentication failed for user "vcap"
DETAIL:  User "vcap" has no password assigned.
        Connection matched pg_hba.conf line 21: "host all all ::/0 md5"
FATAL:  password authentication failed for user "vcap"
DETAIL:  User "vcap" has no password assigned.
        Connection matched pg_hba.conf line 21: "host all all ::/0 md5"
```

**Comment by ramonskie** [comment]
okay solved if i don't supply the -h option than it works

it would be indeed nice to have a option to set a super user in the ctl file
maby a simple if statement will suffice i will try to see if i can set something up if your not already working on it

**Comment by jhunt** [comment]
Ah, yes, vcap is only trusted over the UNIX device, and when you do `-h`, it engages TCP transport.

I'll go ahead and put together a patch to enable role assignments per user, since that's going to be useful for lots of scenarios.
