### ISSUE TITLE
Postgres data directory

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry-community/postgres-boshrelease#31]
Hello,

I'm looking to add a NFS mount to store my postgres data. I believe I can use the [NFS Job](https://bosh.io/jobs/nfs_mounter?source=github.com/cloudfoundry/cf-release&version=215) but I was wondering where/what directory I should mount as the NFS share to use with this bosh release. I don't see it documented and I tried looking around the files/folders.

Thank you.

**Comment by jhunt** [comment]
Postgres' data root is `/var/vcap/store/postgres/db` (see https://github.com/cloudfoundry-community/postgres-boshrelease/blob/master/jobs/postgres/templates/bin/ctl#L28)

You may also want to look at https://github.com/jhunt/nfs-boshrelease/blob/master/jobs/nfs-client/spec, which uses a pre-start script to make sure the volumes are mounted before BOSH monit starts any jobs.

**Comment by braunsonm** [comment]
Does the official NFS mounting not do that already? https://bosh.io/jobs/nfs_mounter?source=github.com/cloudfoundry/cf-release&version=215

My plan was to use the NFS Mounter. Thank you for the data directory btw, exactly what i was looking for :)

**Comment by jhunt** [comment]
Best of luck!
