### ISSUE TITLE
HA deployment option able to achieve same results with BOSH-dns?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/postgres-boshrelease#33]
Instead of using keepalived & haproxy to present a single IP to consumers, would it theoretically be possible to serve up the node pair with a single DNS hostname using bosh-dns and have traffic be routed to each? I suppose it depends on whether each can accept writes at the same time.

This isn't the most well thought out github issue, and I'm really only familiar with leader-follower database topologies (which has a single `write`-enabled node with the rest as read replicas) as opposed to full-HA, so apologies if I sound like a dingus. I'll do some more of my own research into this later, but just figured I'd pose the question to anyone who might have thought or opinions on it 👍

**Comment by jhunt** [comment]
Does this work for off-box, non-BOSH things to hit the single DNS endpoint?

**Comment by aegershman** [comment]
So what I had in mind was for deployments & apps in the same bosh director context which all had network connectivity & would have shared bosh-dns resolution... but dns resolution isn't really the problem, I suppose; I wasn't really thinking through the fact that even with full sync replication, you can't just shove write requests to either leader or follower and expect the followers to redirect those requests to the leader. Nor, as far as I'm aware, a way for nodes in a deployment to "inform" bosh-dns of which node should be routed to.

... so nevermind 😉
