### ISSUE TITLE
Postgres instance does not start

### ISSUE THREAD

**Issue by styjdt** [cloudfoundry-community/postgres-boshrelease#8]
Hi,
I just tried this bosh release of Postgres on AWS EC2 with 1 instance with the following outcome:
The bosh deploy task eventually fails with `postgres/0 (some id)' is not running after update. Review logs ...

Attached you can find the logs
[bosh_deploy.logs.zip](https://github.com/cloudfoundry-community/postgres-boshrelease/files/432494/bosh_deploy.logs.zip)

The postgres.log shows the most probable candidate for the failure: in /var/vcap/jobs/postgres/config/hba.conf some logic produces wrong results.
The logic in postgres-boshrelease/jobs/postgres/templates/config/hba.conf is

```
# postgres hba configuration

# base connectivity for psql
local all vcap trust

# base connectivity for pgpool
local all all md5
<% p("postgres.pgpool.pool", []).each do |ip|
%>host all all <%= ip %>/32 md5
<% end %>

# replication hosts
<% link("db").instances.each do |instance|
%>host replication replication <%= instance.address %>/32 trust
<% end %>

# user-configured acls
<% p("postgres.hba", []).each do |acl| %><%= acl %>
<% end %>
```

but the resulting file in /var/vcap/jobs/postgres/config/hba.conf is

```
# postgres hba configuration

# base connectivity for psql
local all vcap trust

# base connectivity for pgpool
local all all md5


# replication hosts
host replication replication /32 trust


# user-configured acls
host all all 0.0.0.0/0 md5
host all all ::/0 md5
```

where the replication line eventually causes the failure. This instance.address logic is not really working?

I do not understand half of the stuff what's going on in all the scripts, just wanted to try and deploy an instance with this bosh release. Can you point me in some direction, if it could be some misconfiguration at my side or if it is some bug in the bosh release code?

Best
Alexander

**Comment by jhunt** [comment]
Curious; it looks like something is using the 'db' link but has no instance address, causing the configuration to be borked.

Can you provide a copy of the deployment manifest that is exhibiting this problem?

**Comment by styjdt** [comment]
Sure:
[postgres-aws-ec2-manifest.yml.txt](https://github.com/cloudfoundry-community/postgres-boshrelease/files/432774/postgres-aws-ec2-manifest.yml.txt)

What I forgot to mention is that during creation of that manifest using `make_manifest aws-ec2` I encountered:

```
1 error(s) detected:
 - $.jobs.smoke-tests.networks: please set smoke-tests networks
```

And since I did not know what to enter, I simply removed the smoke-tests part from `templates/jobs.yml` :smile: . Hopefully that is not a problem ...

**Comment by jhunt** [comment]
What happens if you assign your postgres job a static IP in a manual network?

**Comment by styjdt** [comment]
Sorry, I'm not anymore on this topic.
So if you don't mind, we could close the ticket.
