### ISSUE TITLE
Creating new user, pool_passwd file does not contain an entry for

### ISSUE THREAD

**Issue by slowbackspace** [cloudfoundry-community/postgres-boshrelease#9]
I tried to use this postgres release with https://github.com/caxqueiroz/postgresql-cf-service-broker.
Everything seemed to work (user and database were created just fine) except that I couldn't connect to the postgres server with credentials binded to cf app. 
```
psql -h 192.168.3.100 -U 24fc5cb7-a0f0-47e7-8be7-3ce80cbd7306 24fc5cb7-a0f0-47e7-8be7-3ce80cbd7306
psql: FATAL:  md5 authentication failed
DETAIL:  pool_passwd file does not contain an entry for "24fc5cb7-a0f0-47e7-8be7-3ce80cbd7306"
```

So I tried to manually create a new user and database with psql just to see if it works. 
`create user testuser with password 'testpass';`
(Broker uses `ALTER ROLE \"" + serviceInstanceId + "\" LOGIN password '" + passwd + "'`)
Result is the same. 
```
psql -h 192.168.3.100 -U testuser  testdb
psql: FATAL:  md5 authentication failed
DETAIL:  pool_passwd file does not contain an entry for "testuser"
```
File `/var/vcap/jobs/pgpool/config/passwd` really does not contain required entry.
I noticed that the passwd file is filled with users defined in pgpool.users in the manifest file (and it does work with "porcupine" user).   
But it is also supposed to work with users created directly in the database, right? If not then It can't be really used with CF service broker... What am I missing?

Properties for postgres job from manifest file
```
properties:
    pcp:
      system_password: secret
    pgpool:
      backend:
        port: 6432
      config:
        enable_pool_hba: true
        port: 5432
      databases:
      - extensions:
        - citext
        - pgcrypto
        name: cf
        users:
        - porcupine
      debug: true
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      users:
      - password: quill
        username: porcupine
      - password: if-ya-got-em
        username: smoke-tests
    postgres:
      config:
        port: 6432
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      replication:
        enabled: true
```

**Comment by jhunt** [comment]
You are correct.  This BOSH release cannot be used with that service broker, since that service broker doesn't know about pgpool, and pgpool has to be updated when new users are added / passwords are changed.
